// USER SESSION
export const USER_TOKEN = 'USER_TOKEN';
export const IS_VERIFIED='IS_VERIFIED';
export const SIGNUPRESPONSE='SIGNUPRESPONSE'
export const AGENT_USER_ID = 'AGENT_USER_ID'
// LOGOUT 
export const LOGOUT = 'LOGOUT'